---
- name: "Red Hat JBoss Web Server installation and configuration"
  hosts: "all"
  become: yes
  vars:
    tomcat_setup: true
    # comment the next line if you another install method
    jws_version: 5.4.0
    # uncomment the two next line if you want to install using RPM on a RHEL system.
    #tomcat_install_method: rpm
    #tomcat_home: /opt/rh/jws5/root/usr/share/tomcat/
    #
    # uncomment the line below if you want to install fetching zipfiles from RHN directly
    #tomcat_install_method: rhn_zipfiles
    # note that workdir is only used when installing from zipfiles
    workdir: /opt
    tomcat_java_version: 1.8.0
  collections:
    - middleware_automation.jws
  roles:
    - jws
    - sabre1041.redhat-csp-download
  tasks:
