---
- name: "Apache Tomcat Common Criteria Validation"
  hosts: localhost
  vars:
    tomcat_setup: true
    tomcat_version: 9.0.39
    workdir: /opt
    tomcat:
      user: tomcat_admin
      group: tomcat
      home: "{{ lookup('env','CATALINA_HOME') }}"
      conf:
        properties: "./conf/catalina.properties"
        policy: "./conf/catalina.policy"
        logging: "./conf/logging.properties"
      archive_url: "https://downloads.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.zip"
      shutdown:
        port: "8999"
  roles:
    - tomcat
    - common_criteria_tomcat
  tasks:
