---
- name: "Red Hat JBoss Web Server installation and configuration"
  hosts: "all"
  become: yes
  vars:
    tomcat_setup: true
    jws_version: 5.4.0
    #uncomment the two next line if you want to install using RPM on a RHEL system.
    #tomcat_install_method: rpm
    #tomcat_home: /opt/rh/jws5/root/usr/share/tomcat/
    workdir: /opt
    tomcat_java_version: 1.8.0
    tomcat_vault:
      name: vault.keystore
      enable: "{{ override_tomcat_vault_enable | default('True') }}"
      alias: my_vault
      storepass: 123456
    mod_cluster:
      enable: "{{ override_tomcat_modcluster_enable | default('True') }}"
      ip: 127.0.0.1
      port: 6666

  roles:
    - tomcat
  tasks:
