---
- name: Check arguments
  ansible.builtin.assert:
    that:
      - tomcat.service.name is defined
    quiet: true

- name: "Enable tomcat service"
  ansible.builtin.service:
    name: "{{ tomcat.service.name }}"
    enabled: yes

- name: "Start tomcat service"
  ansible.builtin.service:
    name: "{{ tomcat.service.name }}"
    state: started
