---
- name: Check arguments
  ansible.builtin.assert:
    that:
      - tomcat.service.name is defined
    quiet: true

- name: "Stop tomcat service"
  ansible.builtin.service:
    name: "{{ tomcat.service.name }}"
    state: stopped
