---
- name: Check arguments
  ansible.builtin.assert:
    that:
      - jws.service.name is defined
    quiet: true

- name: "Stop jws.service"
  become: "{{ jws_install_requires_become | default(true) }}"
  ansible.builtin.service:
    name: "{{ jws.service.name }}"
    state: stopped
