---
- assert:
    that:
      - tomcat.service is defined
      - tomcat.user is defined
      - tomcat.group is defined
      - tomcat.service.conf is defined
      - tomcat.service.script is defined

- name: "Ensures requirements for systemd"
  include_tasks: fastpackage.yml
  vars:
    package_name: "{{ item }}"
  loop:
    - systemd
    - procps

- name: "Ensures service script is deployed"
  template:
    src: templates/systemd/service.sh.j2
    dest: "{{ tomcat.service.script }}"
    owner: "{{ tomcat.user }}"
    group: "{{ tomcat.group }}"
    mode: 0755

- name: "Ensures service configurations files is deployed: {{ tomcat.service.conf }}"
  template:
    src: templates/systemd/tomcat.conf.j2
    dest: "{{ tomcat.service.conf }}"
    owner: "{{ tomcat.user }}"
    group: "{{ tomcat.group }}"
    mode: 0755
  notify:
    - Systemd reload
    - Ensures Tomcat runs under systemd

- name: "Ensures systemd service is configured"
  template:
    src: templates/systemd/tomcat.service.j2
    dest: "{{ tomcat.service.systemd }}"
    owner: "{{ tomcat.user }}"
    group: "{{ tomcat.group }}"
    mode: 0755
  notify:
    - Systemd reload
    - Ensures Tomcat runs under systemd
