---
- name: "Red Hat JBoss Web Server installation and configuration"
  hosts: all
  vars_files:
    - ../../playbooks/vars.yml
  roles:
    - name: middleware_automation.jws.jws

- name: "Red Hat JBoss Web Server uninstallation"
  hosts: all
  collections:
    - middleware_automation.jws
  post_tasks:
    - include_role:
        name: jws
        tasks_from: uninstall.yml
