---
- name: Verify
  hosts: all
  tasks:
    - name: Include jws role defaults
      ansible.builtin.include_vars:
        file: roles/jws/defaults/main.yml
    - name: "Read info on server home: {{ jws_home }}"
      ansible.builtin.stat:
        path: "{{ jws_home }}/lib"
      register: tc_home

    - name: "Check that server home has been removed"
      ansible.builtin.assert:
        that:
          - tc_home is defined
          - tc_home.stat is defined
          - tc_home.stat.exists is defined
          - not tc_home.stat.exists
        quiet: true
