---
- name: Read the content of catalina.out
  ansible.builtin.slurp:
    src: "{{ tomcat_home }}/{{ tomcat_catalina_logfile }}"
  register: catalina_out

- name: Print the content of catalina.out
  ansible.builtin.debug:
    msg: "{{ catalina_out['content'] | b64decode | length }}"

- name: Fail if logfile contains ERRORs
  assert:
    that:
      - "{{ 'ERROR' not in catalina_out.content }}"
    quiet: true
    fail_msg: "Catalina logfile contains ERROR lines."

- name: Fail if native is installed but fails to start
  assert:
    that:
      - "{{ 'Loaded Apache Tomcat Native library' in catalina_out.content }}"
    quiet: true
    fail_msg: "Tomcat native extensions failed to load."
  when: tomcat_native
