---
- name: Prepare
  hosts: all
  tasks:

    - name: Display Ansible version
      ansible.builtin.debug:
        msg: "Ansible version is  {{ ansible_version.full }}"

    - name: "Deploy https certificate"
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/ssl/
      loop:
        - ./resources/keystore.jks

    - name: Install sudo
      ansible.builtin.yum:
        name: sudo
        state: present
