---
- name: Check arguments
  ansible.builtin.assert:
    that:
      - path_to_zipfile_on_target is defined
      - path_to_zipfile_local is defined
    quiet: true

- name: "Check downloaded archive on controller: {{ path_to_zipfile_local }}"
  ansible.builtin.stat:
    path: "{{ path_to_zipfile_local }}"
  register: local_archive_path
  delegate_to: localhost

- name: "Check download archive path on target: {{ path_to_zipfile }}"
  ansible.builtin.stat:
    path: "{{ path_to_zipfile_on_target }}"
  register: archive_path

- name: "Retrieve zipfile from RHN (if credentials provided)"
  block:

    - name: "Checking RHN credentials have been set before attemping to download archives."
      ansible.builtin.assert:
        that:
          - zipfile_url is defined
          - zipfile_url | length > 0
        quiet: True

    - name: "Install JWS with zipfile from RHN: {{ zipfile_url }}"
      redhat_csp_download:
        url: "{{ zipfile_url }}"
        dest: "{{ path_to_zipfile_local }}"
        username: "{{ rhn_username }}"
        password: "{{ rhn_password }}"
      delegate_to: localhost
  when:
    - rhn_username is defined and rhn_username | length > 0
    - rhn_password is defined and rhn_password | length > 0
    - not local_archive_path.stat.exists

- name: "Copy archives to target nodes: {{ path_to_zipfile_on_target }}"
  ansible.builtin.copy:
    src: "{{ path_to_zipfile_local }}"
    dest: "{{ path_to_zipfile_on_target }}"
    owner: "{{ jws.user }}"
    group: "{{ jws.group }}"
    mode: 0640
  when:
    - archive_path is defined
    - archive_path.stat is defined
    - not archive_path.stat.exists
    - local_archive_path.stat is defined
    - local_archive_path.stat.exists
  become: yes
