---
- name: Check download archive path
  ansible.builtin.stat:
    path: "{{ tomcat_install_dir }}/{{ tomcat_zipfile }}"
  register: archive_path

- name: Check local download archive path
  ansible.builtin.stat:
    path: "{{ lookup('env', 'PWD') }}"
  register: local_path
  delegate_to: localhost

- name: Check downloaded archive
  ansible.builtin.stat:
    path: "{{ local_path.stat.path }}/{{ tomcat_zipfile }}"
  register: local_archive_path
  delegate_to: localhost

- name: Copy archive to target nodes
  ansible.builtin.copy:
    src: "{{ local_path.stat.path }}/{{ tomcat_zipfile }}"
    dest: "{{ tomcat_install_dir }}/{{ tomcat_zipfile }}"
    owner: "{{ tomcat.user }}"
    group: "{{ tomcat.group }}"
    mode: 0640
  register: new_version_downloaded
  when:
    - not archive_path.stat.exists
    - local_archive_path.stat is defined
    - local_archive_path.stat.exists
  become: yes
