---
- name: Check arguments
  assert:
    that:
      - tomcat.rhn.server_zipfile_url is defined
      - tomcat.rhn.server_zipfile_url | length > 0
    quiet: true
    fail_msg: "You need to provide"

- set_fact:
    tomcat_zipfile: "jws-{{ jws_version }}-application-server.zip"
    native_zipfile: "jws-{{ jws_version }}-application-server-RHEL{{ ansible_facts['distribution_major_version'] }}-x86_64.zip"
  when:
    - jws_version is defined

- name: "Install JWS with zipfile from RHN: {{ tomcat.rhn.server_zipfile_url }}"
  redhat_csp_download:
    url: "{{ tomcat.rhn.server_zipfile_url }}"
    dest: "{{ tomcat_zipfile }}"
    username: "{{ tomcat.rhn.username }}"
    password: "{{ tomcat.rhn.password }}"

- name: "Install JWS native dependencies with zipfile from RHN: {{ tomcat.rhn.native_zipfile_url }}"
  redhat_csp_download:
    url: "{{ tomcat.rhn.native_zipfile_url }}"
    dest: "{{ native_zipfile }}"
    username: "{{ tomcat.rhn.username }}"
    password: "{{ tomcat.rhn.password }}"
  when:
    - native_zipfile_url is defined
    - native_zipfile_url | length > 0
