---
- name: "Set patch_version and jws_patch_bundle if not provided and distribution data are available."
  when:
    - not jws_patch_bundle is defined or 'reset' in jws_patch_bundle
    - jws_version is defined
    - ansible_facts is defined
    - ansible_facts['distribution_major_version'] is defined
  block:
    - name: "Set patch_version using distribution datas."
      ansible.builtin.set_fact:
        patch_version: "{{ jws.rhn_ids[jws_version].latest_cp.v }}"

    - name: "Set patch_bundle using distribution datas."
      ansible.builtin.set_fact:
        jws_patch_bundle: "jws-{{ patch_version }}{{ archive_file_suffix | default('.zip') }}"

- name: "Set download URLs variables (if not provided)."
  when:
    - jws_version is defined
    - jws.rhn_ids is defined
  block:
    - name: "Set zipfile download URL."
      when:
        - not rhn_cpatch_zipfile_url is defined
      block:
        - name: "Ensure version {{ jws_version }} exists in available metadatas."
          ansible.builtin.assert:
            that:
              - jws.rhn_ids[jws_version] is defined
              - jws.rhn_ids[jws_version].id is defined
            quiet: True
            fail_msg: "No version {{ jws_version }} within the metadata of this collection."

    - name: "Set download URL for native (if requested)."
      when:
        - jws_native is defined
        - jws_native
      block:
        - name: "Ensure version {{ jws_version }} exists in available metadatas."
          ansible.builtin.assert:
            that:
              - jws.rhn_ids[jws_version] is defined
              - jws.rhn_ids[jws_version].native is defined
            quiet: True
            fail_msg: "No version {{ jws_version }} within the metadata of this collection."

- name: "Set path to local patch bundle"
  ansible.builtin.set_fact:
    downloaded_patch_bundle_file: "{{ jws_archive_repository }}/{{ jws_patch_bundle }}"
  when:
    - not downloaded_patch_bundle_file is defined or 'reset' in downloaded_patch_bundle_file
