---
- name: "Set path to local patch bundle"
  ansible.builtin.set_fact:
    downloaded_patch_bundle_file: "{{ jws_archive_repository }}/{{ jws_patch_bundle }}"
  when:
    - not downloaded_patch_bundle_file is defined or 'reset' in downloaded_patch_bundle_file
