---
- name: Verify
  hosts: instance
  collections:
    - middleware_automation.jws
  roles:
    - role: jws_validation
      jws_home: /opt/apache-tomcat-9.0.65
      jws_service_name: tomcat
      jws_java_version: 11
