---
- include_tasks: tasks/assert_no_result_with_xpath.yml
  loop:
    - { xpath: "//*[@allowLink]", xmlfile: "{{ item.path }}", error: "Atttribute allowLink SHOULD NOT be set or set to true", success: "Attribute allowLink is properly configured." }
    - { xpath: "//*[@allowLink=true]", xmlfile: "{{ item.path }}", error: "Atttribute allowLink SHOULD NOT be set or set to true", success: "Attribute allowLink is properly configured." }
    - { xpath: "//*[@crossContext]", xmlfile: "{{ item.path }}", error: "Atttribute crossContext SHOULD NOT be set or set to true", success: "Attribute allowLink is properly configured." }
    - { xpath: "//*[@crossContext=true]", xmlfile: "{{ item.path }}", error: "Atttribute crossContext SHOULD NOT be set or set to true", success: "Attribute allowLink is properly configured." }

