---
- name: Systemd reload
  ansible.builtin.systemd:
    daemon_reload: yes
  when:
    - tomcat.service is defined
    - tomcat.service.enabled is defined
    - tomcat.service.enabled

- name: Ensures Tomcat runs under systemd
  include_tasks: tasks/systemd/service.yml
  when:
    - tomcat.service is defined
    - tomcat.service.enabled is defined
    - tomcat.service.enabled

- name: Restart Tomcat service
  service:
    name: "{{ tomcat.service.name }}"
    state: restarted
  when:
    - tomcat.service is defined
    - tomcat.service.enabled is defined
    - tomcat.service.enabled
