---
driver:
  name: podman

platforms:
  - name: instance-rhel10
    image: registry.access.redhat.com/ubi10/ubi-init:latest
    command: "/usr/sbin/init"
    pre_build_image: true
    privileged: true

  - name: instance-rhel9
    image: registry.access.redhat.com/ubi9/ubi-init:latest
    command: "/usr/sbin/init"
    pre_build_image: true

  - name: instance-rhel8
    image: registry.access.redhat.com/ubi8/ubi-init:latest
    command: "/usr/sbin/init"
    pre_build_image: true
    privileged: true

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
    ssh_connection:
      pipelining: false
  inventory:
    host_vars:
      localhost:
        ansible_python_interpreter: "{{ ansible_playbook_python }}"
      instance-rhel10:
        jws_java_version: 21
        ansible_connection: podman
      instance-rhel9:
        jws_java_version: 17
        ansible_connection: podman
      instance-rhel8:
        jws_java_version: 11
        ansible_connection: podman
        ansible_python_interpreter: /usr/bin/python3.9
