---
- name: Check arguments
  assert:
    that:
      - tomcat is defined
      - tomcat.install_method is defined
      - tomcat.install_method in tomcat.supported_install_method
    quiet: true
    fail_msg: "{{ tomcat.install_method }} does not exist or is not supported. Supported methods are: {{ tomcat.supported_install_method }}"

- debug:
    msg: "Install method: {{ tomcat.install_method }}"

- include_tasks: install/rhn.yml
  when:
    - tomcat.install_method == 'rhn_zipfiles'

- include_tasks: install/url.yml
  when:
    - tomcat.install_method == 'zipfiles'

- include_tasks: install/zipfiles.yml
  when:
    - tomcat.install_method == 'local_zipfiles' or tomcat.install_method == 'rhn_zipfiles' or tomcat.install_method == 'zipfiles'

- include_tasks: install/rpm.yml
  when:
    - tomcat.install_method == 'rpm'
