---
- name: "Red Hat JBoss Web Server installation and configuration"
  hosts: all
  become: True
  vars_files:
    - vars.yml
  roles:
    - name: middleware_automation.jws.jws
    - name: middleware_automation.jws.jws_validation
