---
- name: "Red Hat JBoss Web Server validation"
  hosts: all
  become: "{{ jws_install_requires_become | default(true) }}"
  vars_files:
    - vars.yml
  roles:
    - middleware_automation.jws.jws_validation
