---
tomcat_setup: true
tomcat_install_method: zipfiles
tomcat_version: 9.0.50
tomcat_java_version: 1.8.0
tomcat_listen_http_bind_address: 127.0.0.1
tomcat_systemd_enabled: True
tomcat_service_name: tomcat
tomcat_service_systemd_type: forking
ansible_distribution: 'RedHat'
